apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: steam-insight

resources:
- ../../base

commonLabels:
  environment: dev

images:
- name: WAS_IMAGE
  newName: 827913617635.dkr.ecr.us-east-2.amazonaws.com/steam-insight-dev/was
  newTag: 4f7faf84a60b
- name: WEB_IMAGE
  newName: 827913617635.dkr.ecr.us-east-2.amazonaws.com/steam-insight-dev/web
  newTag: 4f7faf84a60b
